//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickUp.HomeTasks.Day1.DB.db_first
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public Groups()
        {
            this.Students = new HashSet<Students>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public string Faculty { get; set; }
    
        public virtual ICollection<Students> Students { get; set; }
    }
}
